
import { getCityData } from "@/lib/data";
import { notFound } from "next/navigation";
import CityHero from "@/components/CityHero";
import WeatherDashboard from "@/components/WeatherDashboard";
import DayVerdict from "@/components/DayVerdict";
import { format } from "date-fns";
import type { Metadata } from 'next';
import Link from "next/link";
import DatePageTracker from "@/components/DatePageTracker";
import SwipeNavigation from "@/components/SwipeNavigation";
import Header from "@/components/common/Header";
import DayTravelInfo from "@/components/DayTravelInfo";

const MONTH_MAP: Record<string, string> = {
    january: '01', february: '02', march: '03', april: '04', may: '05', june: '06',
    july: '07', august: '08', september: '09', october: '10', november: '11', december: '12'
};

export const dynamicParams = true;
export const revalidate = 86400;

function getDateUrl(date: Date, city: string) {
    const monthName = format(date, 'MMMM').toLowerCase();
    const day = date.getDate();
    return `/${city}/${monthName}/${day}`;
}

export async function generateMetadata({ params }: { params: { city: string; month: string; day: string } }): Promise<Metadata> {
    const { city, month, day } = params;
    const monthLower = month.toLowerCase();
    const monthNum = MONTH_MAP[monthLower];
    const dayPad = day.toString().padStart(2, '0');

    if (!monthNum) return { title: 'Date not found' };

    const data = await getCityData(city);
    if (!data) return { title: 'City not found' };

    const dateKey = `${monthNum}-${dayPad}`;
    const dayData = data.days[dateKey];
    if (!dayData) return { title: 'Date not found' };

    const cityName = data.meta.name;
    const monthDisplay = monthLower.charAt(0).toUpperCase() + monthLower.slice(1);

    const tempAvg = dayData.stats.temp_max;
    const rainProb = dayData.stats.precip_prob;

    // Calculate monthly pressure score (relative to peak month)
    const calculateMonthlyPressure = (): number => {
        if (!data.meta.flight_info?.seasonality) return 0;

        const seasonality = data.meta.flight_info.seasonality;
        const currentMonthFlights = seasonality[parseInt(monthNum)] || 0;
        const allValues = Object.values(seasonality).filter(v => v > 0);

        if (allValues.length === 0 || currentMonthFlights === 0) return 0;

        const maxFlights = Math.max(...allValues);
        // Calculate percentage of peak and scale to 0-100
        const percentOfPeak = (currentMonthFlights / maxFlights) * 100;

        return Math.round(percentOfPeak);
    };

    // NEW: Enhanced SEO with tourism and health context
    const monthlyFlightPressure = calculateMonthlyPressure();
    const holidayEvent = dayData.events?.[0]?.description;
    const vaccineCount = data.meta.health_info?.vaccines?.length || 0;

    // Shortened month name for SEO (e.g., "November" → "Nov")
    const monthShort = monthDisplay.length > 4 ? monthDisplay.substring(0, 3) : monthDisplay;

    // Build dynamic description extras (keep concise for 140-155 char limit)
    let seasonContext = "";
    if (monthlyFlightPressure >= 70) {
        seasonContext = "Peak season - book early.";
    } else if (monthlyFlightPressure < 30) {
        seasonContext = "Off-peak with fewer crowds.";
    } else {
        seasonContext = "Moderate tourist activity.";
    }

    // Optional: Add holiday context if present (but watch length)
    let holidayNote = "";
    if (holidayEvent && holidayEvent.length < 30) {
        holidayNote = ` ${holidayEvent}.`;
    }

    // SEO-optimized title (target: 50-60 chars)
    // Format: "City Mon DD Weather: 17°C, 19% Rain | 30-Year Data"
    const title = `${cityName} ${monthShort} ${day} Weather: ${tempAvg}°C, ${rainProb}% Rain | 30-Year Data`;

    // SEO-optimized description (target: 140-155 chars)
    // Format: "City Mon DD: 17°C avg, 19% rain chance. Season context. 30-year NASA climate data for travel planning."
    const description = `${cityName} ${monthShort} ${day}: ${tempAvg}°C avg, ${rainProb}% rain chance. ${seasonContext}${holidayNote} 30-year NASA climate data for travel planning.`;

    return {
        title: title,
        description: description,
        openGraph: {
            title: `${cityName} Weather: ${day} ${monthDisplay}`,
            description: `Historical data shows ${tempAvg}°C, ${rainProb}% rain risk.`,
            type: 'website',
            locale: 'en_US',
            siteName: '30YearWeather',
            // images are auto-generated by opengraph-image.tsx
        },
        twitter: {
            card: 'summary_large_image',
            title: `${cityName} Weather: ${day} ${monthDisplay}`,
            description: `Historical data: ${tempAvg}°C, ${rainProb}% rain risk.`,
            // images are auto-generated by opengraph-image.tsx
        },
        alternates: {
            canonical: `/${city}/${monthLower}/${day}`,
        }
    };
}

export default async function CityDayPage({
    params,
}: {
    params: { city: string; month: string; day: string };
}) {
    const { city, month, day } = params;
    const monthLower = month.toLowerCase();
    const monthNum = MONTH_MAP[monthLower];
    const monthDisplay = monthLower.charAt(0).toUpperCase() + monthLower.slice(1);

    if (!monthNum) notFound();

    const data = await getCityData(city);
    if (!data) notFound();

    // Helper to calculate offset dynamically from IANA string (e.g. "Asia/Makassar" -> 8)
    const getTzOffset = (tzName: string) => {
        try {
            const now = new Date();
            const utcDate = new Date(now.toLocaleString('en-US', { timeZone: "UTC" }));
            const tzDate = new Date(now.toLocaleString('en-US', { timeZone: tzName }));
            return Math.round((tzDate.getTime() - utcDate.getTime()) / 36e5);
        } catch (e) {
            return 2; // Default fallback
        }
    };
    const calculatedOffset = getTzOffset(data.meta.timezone || 'UTC');

    const dayPad = day.toString().padStart(2, '0');
    const dateKey = `${monthNum}-${dayPad}`;
    const dayData = data.days[dateKey];

    if (!dayData) notFound();

    // Date Object for calculations
    const dateObj = new Date(2024, parseInt(monthNum) - 1, parseInt(day));
    const formattedDate = format(dateObj, "MMMM d");

    // Calculate monthly pressure score (relative to peak month)
    const calculateMonthlyPressure = (): number => {
        if (!data.meta.flight_info?.seasonality) return 0;

        const seasonality = data.meta.flight_info.seasonality;
        const currentMonthFlights = seasonality[parseInt(monthNum)] || 0;
        const allValues = Object.values(seasonality).filter(v => v > 0);

        if (allValues.length === 0 || currentMonthFlights === 0) return 0;

        const maxFlights = Math.max(...allValues);
        // Calculate percentage of peak and scale to 0-100
        const percentOfPeak = (currentMonthFlights / maxFlights) * 100;

        return Math.round(percentOfPeak);
    };

    const monthlyFlightPressure = calculateMonthlyPressure();

    // Navigation
    const prevObj = new Date(dateObj); prevObj.setDate(prevObj.getDate() - 1);
    const nextObj = new Date(dateObj); nextObj.setDate(nextObj.getDate() + 1);
    const prevUrl = getDateUrl(prevObj, city);
    const nextUrl = getDateUrl(nextObj, city);

    // Verdict Logic
    const weddingScore = dayData.scores.wedding;
    let verdict = "MAYBE";
    if (weddingScore >= 80) verdict = "YES";
    else if (weddingScore < 40) verdict = "NO"; // More strict

    // Alternative Dates
    const alternativeDates = [];
    for (let offset = -7; offset <= 7; offset++) {
        if (offset === 0) continue;
        const altDate = new Date(dateObj);
        altDate.setDate(altDate.getDate() + offset);
        const altKey = `${(altDate.getMonth() + 1).toString().padStart(2, '0')}-${altDate.getDate().toString().padStart(2, '0')}`;
        const altDayData = data.days[altKey];
        if (altDayData) {
            alternativeDates.push({
                dateSlug: getDateUrl(altDate, city), // Use full URL here or just slug? Component expects slug probably?
                // Wait, WeatherDashboard expects dateSlug to match URL format?
                // Let's optimize: WeatherDashboard usually links to something.
                // We should pass the URL.
                // But the component might render <Link href={base + slug}>.
                // Let's pass the RELATIVE path parts.
                // Actually, let's look at WeatherDashboard usage.

                // For now, I will pass the raw MM-DD slug but let the component handle it?
                // No, component probably builds link `/city/MM-DD`. That's BROKEN now.
                // I need to update WeatherDashboard to support new URLs.
                // OR hacked solution: pass full URL as slug? No.

                dateFormatted: format(altDate, "MMMM d"),
                score: altDayData.scores.wedding,
                tempMax: altDayData.stats.temp_max,
                precipProb: altDayData.stats.precip_prob,
                improvement: altDayData.scores.wedding - weddingScore,
                // Passing custom Link href prop if component supports it?
                linkHref: getDateUrl(altDate, city)
            });
        }
    }

    // Popular Cities Comparison
    const popularCities = [
        { slug: 'prague', name: 'Prague', country: 'Czech Republic' }, // Updated slugs!
        { slug: 'paris', name: 'Paris', country: 'France' },
        { slug: 'rome', name: 'Rome', country: 'Italy' },
        { slug: 'barcelona', name: 'Barcelona', country: 'Spain' },
        { slug: 'london', name: 'London', country: 'United Kingdom' },
        { slug: 'amsterdam', name: 'Amsterdam', country: 'Netherlands' },
        { slug: 'lisbon', name: 'Lisbon', country: 'Portugal' },
        { slug: 'tokyo', name: 'Tokyo', country: 'Japan' },
        { slug: 'dubai', name: 'Dubai', country: 'UAE' },
        { slug: 'bangkok', name: 'Bangkok', country: 'Thailand' },
        { slug: 'bali', name: 'Bali', country: 'Indonesia' }, // Added Bali
        { slug: 'new-york', name: 'New York', country: 'USA' },
        { slug: 'cancun', name: 'Cancún', country: 'Mexico' }
    ].filter(c => c.slug !== city);

    const cityComparisons = await Promise.all(
        popularCities.slice(0, 6).map(async (c) => {
            const cityData = await getCityData(c.slug);
            if (!cityData || !cityData.days[dateKey]) return null;
            const dayStats = cityData.days[dateKey];
            return {
                citySlug: c.slug,
                cityName: c.name,
                country: c.country,
                tempMax: dayStats.stats.temp_max,
                precipProb: dayStats.stats.precip_prob,
                score: dayStats.scores.wedding
                // Link? Dashboard builds link.
            };
        })
    ).then(results => results.filter((r): r is NonNullable<typeof r> => r !== null));

    return (
        <SwipeNavigation prevUrl={prevUrl} nextUrl={nextUrl} className="min-h-screen bg-slate-50">
            <DatePageTracker
                cityName={data.meta.name}
                date={formattedDate}
                verdict={verdict}
            />
            {/* Structured Data: WeatherForecast, Breadcrumbs, FAQ */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify([
                        {
                            "@context": "https://schema.org",
                            "@type": "WeatherForecast",
                            "name": `${data.meta.name} Weather on ${monthDisplay} ${day}`,
                            "url": `https://30yearweather.com/${city}/${monthLower}/${day}`,
                            "temperature": `${dayData.stats.temp_max}°C`,
                            "precipitationProbability": (dayData.stats.precip_prob / 100).toFixed(2),
                            "dateIssued": `2025-${monthNum}-${dayPad}`,
                            "about": {
                                "@type": "Place",
                                "name": data.meta.name,
                                "address": {
                                    "@type": "PostalAddress",
                                    "addressCountry": data.meta.country || "Global"
                                }
                            },
                            "dataSource": {
                                "@type": "Dataset",
                                "name": "NASA POWER 1991-2021"
                            },
                            "mainEntity": {
                                "@type": "FAQPage",
                                "mainEntity": [
                                    {
                                        "@type": "Question",
                                        "name": `What is the weather in ${data.meta.name} on ${monthDisplay} ${day}?`,
                                        "acceptedAnswer": {
                                            "@type": "Answer",
                                            "text": `Historically, on ${monthDisplay} ${day}, ${data.meta.name} averages a high of ${dayData.stats.temp_max}°C and a low of ${dayData.stats.temp_min}°C. The probability of rain is ${dayData.stats.precip_prob}%.`
                                        }
                                    },
                                    {
                                        "@type": "Question",
                                        "name": `Does it snow in ${data.meta.name} on ${monthDisplay} ${day}?`,
                                        "acceptedAnswer": {
                                            "@type": "Answer",
                                            "text": dayData.stats.temp_min > 2 ? `No, historically it is too warm for snow in ${data.meta.name} on this date.` : `While rare, temperatures have occasionally dropped low enough for wintry conditions in the past.`
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "@context": "https://schema.org",
                            "@type": "BreadcrumbList",
                            "itemListElement": [
                                { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://30yearweather.com" },
                                { "@type": "ListItem", "position": 2, "name": data.meta.name, "item": `https://30yearweather.com/${city}` },
                                { "@type": "ListItem", "position": 3, "name": monthDisplay, "item": `https://30yearweather.com/${city}/${monthLower}` },
                                { "@type": "ListItem", "position": 4, "name": day.toString(), "item": `https://30yearweather.com/${city}/${monthLower}/${day}` }
                            ]
                        }
                    ])
                }}
            />

            <Header
                breadcrumb={{
                    label: `${data.meta.name}, ${formattedDate}`,
                    href: `/${city}/${monthLower}`,
                    sublabel: "Daily Weather Detail"
                }}
            />

            {/* Hero Section */}
            <CityHero
                city={data.meta.name}
                citySlug={city}
                date={formattedDate}
                tempMax={dayData.stats.temp_max}
                tempMin={dayData.stats.temp_min}
                precipProb={dayData.stats.precip_prob}
                dateSlug={dateKey}
                windKmh={dayData.stats.wind_kmh}
                humidity={dayData.stats.humidity_percent}
                imageAlt={`${data.meta.name} street view during ${monthDisplay}`}
            />

            <article itemScope itemType="https://schema.org/Article" className="max-w-7xl mx-auto">
                <div itemProp="articleBody" className="space-y-12">

                    <DayVerdict
                        score={dayData.scores.wedding}
                        precipProb={dayData.stats.precip_prob}
                        city={data.meta.name}
                        month={format(dateObj, "MMMM")}
                        day={dateObj.getDate()}
                        tempMax={dayData.stats.temp_max}
                        humidity={dayData.stats.humidity_percent || 0}
                        citySlug={city}
                        monthSlug={monthLower}
                        flightPressure={monthlyFlightPressure}
                        holidayName={dayData.events?.[0]?.description || null}
                        vaccineCount={data.meta.health_info?.vaccines?.length}
                    />

                    <WeatherDashboard
                        dayData={dayData}
                        lat={data.meta.lat}
                        lon={data.meta.lon}
                        dateId={dateKey}
                        citySlug={city}
                        cityName={data.meta.name}
                        countryName={data.meta.country}
                        geoInfo={data.meta.geo_info}
                        safetyProfile={data.meta.safety_profile}
                        timezoneOffset={calculatedOffset}
                        alternativeDates={alternativeDates}
                        cityComparisons={cityComparisons}
                        flightInfo={data.meta.flight_info}
                        healthInfo={data.meta.health_info}
                    />
                </div>
            </article>
        </SwipeNavigation>
    );
}
